production pathways:
  wind:
    production volume:
      variable: Production|wind
    ecoinvent alias: 
      name: electricity production, wind, 1-3MW turbine, onshore, renewable energy products
      reference product: electricity, high voltage
      loctation: CH
      exists in original database: True


production pathways:
  nuclear:
    production volume:
      variable: Production|nuclear
    ecoinvent alias:
      name: electricity production, nuclear, pressure water reactor
      reference product: electricity, high voltage
      location: CH
      exists in original database: True


markets:
    # name of the market dataset
  - name: market for electricity, high voltage, test
    # reference product of the market dataset
    reference product: electricity, high voltage
    # unit of the market dataset
    unit: kilowatt hour
    # names of datasets that should compose the market
    includes:
      - wind
      - nuclear
     


 
