production pathways:
  wind:
    production volume:
      variable: Production|wind

    ecoinvent alias: 
      name: electricity production, wind, 1-3MW turbine, onshore
      
      reference product: electricity, high voltage
      exists in original database: True




production pathways:
  nuclear:
    production volume:
      variable: Production|nuclear

    ecoinvent alias:
      name: electricity production, nuclear
      
      reference product: electricity, high voltage
      exists in original database: True


markets:
    # name of the market dataset
  - name: market for electricity, high voltage
    # reference product of the market dataset
    reference product: electricity, high voltage
    # unit of the market dataset
    unit: kilowatt hour
    # names of datasets that should compose the market
    includes:
      - wind
      - nuclear
     


 
